### ISSUE TITLE
Support non-kwargs key-value matching in any_dict.containing()

### ISSUE THREAD

**Issue by markuswustenberg** [toddsifleet/equals#10]
I have a use case where I want to check for certain headers in an HTTP request using `equals` and `doubles`:

```
    headers = any_dict.containing('If-None-Match'='abc')
    (expect(http_client_double)
        .fetch(any_string, method='POST', headers=headers, body=anything, request_timeout=any_number)
        .and_return_future(response)
        .once())
```

Unfortunately, the above fails (of course) because keyword names can't be expressions:

```
E       headers = any_dict.containing('If-None-Match'='abc')
E   SyntaxError: keyword can't be an expression
```

Using `any_dict` differently only checks for keys but "works":

```
    headers = any_dict.containing('If-None-Match')
    (expect(http_client_double)
        .fetch(any_string, method='POST', headers=headers, body=anything, request_timeout=any_number)
        .and_return_future(response)
        .once())
```

Could there be a nice way to add this to `equals`? I'd be happy to implement it myself and do a PR, if someone could think of a good approach that keeps backwards compatibility. Perhaps checking if the argument to `any_dict.containing()` is a `dict` itself? That would break for people checking `dict` values with `dict`s, though.

**Comment by toddsifleet** [comment]
I think you can get around this problem by using pythons `**` operator, e.g.:

`
any_dict.containing(**{'If-None-Match': 'bob-barker'})
`
